# Generated by Django 5.1.4 on 2024-12-11 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_code', models.CharField(max_length=25, unique=True)),
                ('member_name', models.CharField(max_length=50, unique=True)),
                ('first_seen', models.DateTimeField()),
                ('duration', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=25, unique=True)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2024, 12, 11, 13, 0, 23, 38243))),
                ('end_time', models.DateTimeField()),
                ('minutes_of_meeting', models.TextField(max_length=10000)),
                ('attendees', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('emailid', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('Member', 'Member'), ('Co-ordinator', 'Co-ordinator'), ('Lead', 'Lead')], max_length=20)),
                ('regno', models.IntegerField(unique=True)),
            ],
        ),
    ]
