# Generated by Django 5.1.4 on 2024-12-11 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50, unique=True)),
                ('file', models.FileField(upload_to='media/contrib/<django.db.models.fields.CharField>')),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 13, 4, 47, 467148)),
        ),
    ]
