# Generated by Django 5.1.4 on 2024-12-11 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_contribution_alter_meeting_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 13, 15, 25, 508110)),
        ),
    ]
