# Generated by Django 4.2.20 on 2025-06-22 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_meeting_start_time_alter_member_joined_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2025, 6, 22, 17, 15, 27, 108949)),
        ),
        migrations.AlterField(
            model_name='member',
            name='joined_on',
            field=models.DateField(default=datetime.datetime(2025, 6, 22, 11, 45, 27, 108949, tzinfo=datetime.timezone.utc)),
        ),
    ]
