# Generated by Django 5.2rc1 on 2025-04-03 16:23

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('register_no', models.PositiveIntegerField(unique=True)),
                ('sastra_email', models.EmailField(max_length=254)),
                ('branch', models.CharField(max_length=100)),
                ('batch', models.PositiveIntegerField()),
                ('posts', models.CharField(default='[0]', max_length=1000000)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('register_no', models.PositiveIntegerField(unique=True)),
                ('sastra_email', models.EmailField(max_length=254)),
                ('branch', models.CharField(max_length=100)),
                ('batch', models.PositiveIntegerField()),
                ('posts', models.CharField(default='[0]', max_length=1000000)),
                ('password', models.CharField(max_length=20)),
                ('club_role', models.CharField(max_length=40)),
                ('join_date', models.DateField(verbose_name=django.utils.timezone.now)),
                ('contribution_score', models.FloatField(default=0.0)),
                ('attendance_percentage', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000000000)),
                ('author_reg_no', models.PositiveIntegerField(unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 4, 3, 21, 53, 1, 884409))),
                ('verified', models.BooleanField(default=False)),
                ('verified_by', models.PositiveIntegerField()),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
