# Generated by Django 5.2rc1 on 2025-04-06 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_post_date_alter_post_verified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_reg_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 21, 24, 42, 895099)),
        ),
    ]
