# Generated by Django 5.2rc1 on 2025-04-06 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_post_author_reg_no_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 21, 47, 29, 580077)),
        ),
    ]
