# Generated by Django 5.2rc1 on 2025-04-07 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_post_date_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='upvotes',
            field=models.ManyToManyField(blank=True, to='website.member'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 14, 39, 52, 905161)),
        ),
    ]
