# Generated by Django 5.2rc1 on 2025-04-07 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_joinrequest_upvotes_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 14, 54, 22, 374208)),
        ),
    ]
