# Generated by Django 4.2.20 on 2025-06-22 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_post_tags_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 14, 41, 5, 978155)),
        ),
    ]
